### ISSUE TITLE
Using `start_jupyter.sh` does not work.

### ISSUE THREAD

**Issue by hpretl** [iic-jku/IIC-OSIC-TOOLS#59]
When running `start_jupyter.sh`, the VM exits, and the following error is shown in the Docker console:
```
[INFO] SKIPPING UI STARTUP
2024-07-30 11:57:44 [INFO] Executing command: 'jupyter notebook'
2024-07-30 11:57:47 Traceback (most recent call last):
2024-07-30 11:57:47   File "/usr/lib/python3/dist-packages/notebook/traittypes.py", line 232, in _resolve_classes
2024-07-30 11:57:47     klass = self._resolve_string(klass)
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/traitlets/traitlets.py", line 2015, in _resolve_string
2024-07-30 11:57:47     return import_item(string)
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/traitlets/utils/importstring.py", line 33, in import_item
2024-07-30 11:57:47     module = __import__(package, fromlist=[obj])
2024-07-30 11:57:47 ModuleNotFoundError: No module named 'jupyter_server.contents'
2024-07-30 11:57:47 
2024-07-30 11:57:47 During handling of the above exception, another exception occurred:
2024-07-30 11:57:47 
2024-07-30 11:57:47 Traceback (most recent call last):
2024-07-30 11:57:47   File "/usr/bin/jupyter-notebook", line 33, in <module>
2024-07-30 11:57:47     sys.exit(load_entry_point('notebook==6.4.8', 'console_scripts', 'jupyter-notebook')())
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/jupyter_core/application.py", line 283, in launch_instance
2024-07-30 11:57:47     super().launch_instance(argv=argv, **kwargs)
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 1073, in launch_instance
2024-07-30 11:57:47     app = cls.instance(**kwargs)
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/traitlets/config/configurable.py", line 583, in instance
2024-07-30 11:57:47     inst = cls(*args, **kwargs)
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/traitlets/traitlets.py", line 1292, in __new__
2024-07-30 11:57:47     inst.setup_instance(*args, **kwargs)
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/traitlets/traitlets.py", line 1335, in setup_instance
2024-07-30 11:57:47     super(HasTraits, self).setup_instance(*args, **kwargs)
2024-07-30 11:57:47   File "/usr/local/lib/python3.10/dist-packages/traitlets/traitlets.py", line 1311, in setup_instance
2024-07-30 11:57:47     init(self)
2024-07-30 11:57:47   File "/usr/lib/python3/dist-packages/notebook/traittypes.py", line 223, in instance_init
2024-07-30 11:57:47     self._resolve_classes()
2024-07-30 11:57:47   File "/usr/lib/python3/dist-packages/notebook/traittypes.py", line 235, in _resolve_classes
2024-07-30 11:57:47     warn(f"{klass} is not importable. Is it installed?", ImportWarning)
2024-07-30 11:57:47 TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
```

**Comment by hpretl** [comment]
@MrHighVoltage Can you please take a look? Maybe the correct starting statement should be `jupyter lab` instead of `jupyter notebook`?

**Comment by hpretl** [comment]
This is indeed a bug of the current release, need to fix that in the next release.

**Comment by hpretl** [comment]
This is fixed and working in the next release, further instead of `jupyter notebook` now is called `jupyter lab`, see 1af9ad4fb3769feb6bc974598120f418e114328d.
